### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Melissajiayue** [INFO-526-S24/project-final-Datavista#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Varun Sahdev - @solitudevedhas
- Sanja Dmitrovic - @sdmitrovic
- Naitik Shah - [@naitik2608](https://datavizaz-spring2024.slack.com/team/U06D5V33GFL)
- Mohammad Farmani - @mfarmani95
- Jiayue - @Melissajiayue
- Vidhyananth - [@Vidhyananth Sivashanmugam](https://datavizaz-spring2024.slack.com/team/U06DTCENN1Y)

**- Describe the goal of the project.**

The goal of this this project is aims to have a deep understanding of data breaches, their trends, impacts, and vulnerabilities within the realm of cybersecurity with a special focus on the unprecedented surge in data compromises reported in 2023. 

**- Describe the data used or collected.**

The project utilizes the "World’s Biggest Data Breaches & Hacks" dataset from informationisbeautiful.net, covering data breaches across various sectors from 2003 to 2023. This dataset includes key columns like year, date, sector, method, and data sensitivity.

**- Describe how the research question will be answered, e.g. what approaches / methods will be used.**

The research questions focus on assessing how information breaches have evolved over the past decades and identifying vulnerabilities specific to different sectors or data types. To answer those questions, they will do data preprocessing and analyze trends in the data using exploratory data analysis. Finally, they aim to use tools like Shiny and ggplot2 in R to make interactive visualizations within a dashboard. 

**- Is there anything that is unclear from the proposal?**

1.	The company column is not clearly introduced. 
In the introduction, it should be made more clear that the data breaches are affecting companies.
2.	The plan of answering those questions is too general. 
There needs to be more explanation of what specific visualizations will be used and how the user can interact with the dashboard.
3.	The details of designing the shiny dashboard is not very clear. 
A more clear plan of which features the dashboard will include should be outlined.

**- Provide constructive feedback on how the team might be able to improve their project.**
It is currently unclear how the team will define breach severity. There should be an explanation if they are created a new variable for this or if they are defining severity by the number of breaches.

**- What aspect of this project are you most interested in and would like to see highlighted in the presentation.**

We are most interested in 
1.	Which sectors are more prone to what types of attack.
2.	The breaches that happened at major companies like Facebook.

**- Provide constructive feedback on any issues with file and/or code organization.**

1.	There is no link to the full dataset. 
The current link is to the general webpage.
2.	For the “analysis plan” part, they can state the overall outcomes for the visualization before going into the specific questions. For instance, they will have a Shiny dashboard in the end, so the readers can have a better idea of the final product if this is explained in the beginning. 

**- (Optional) Any further comments or feedback?**

Good things: 
1.	The title is designed well. 
2.	There are many interesting topics and data variables to explore. The dashboard will be informative on how to protect our data.

**Comment by Abhi291712** [comment]
Thank you for your valuable feedback.
We have incorporated the changes suggested by you into our proposal.
