### ISSUE TITLE
Proposal peer review by GraphGeeks

### ISSUE THREAD

**Issue by Gowtham-18** [INFO-526-S24/project-final-Datavista#2]
The following is the peer review of the project proposal by GraphGeeks. The team members that participated in this review are 

- Omid Zandi - @zandi-omid
- Devendran Vemula - @vemuladevendran
- Gorantla Sai Laasya - @Sailaasya-1
- Rajitha Reddy - @RAJITHAREDDYTIRUTHANI
- Gowtham Gopalakrishnan - @Gowtham-18
- Mrunali Yadav - @mrunaliyadavps

- Describe the goal of the project.

The goal is to develop an interactive dashboard using R Shiny to detect trends in data breaches and analyze cybersecurity data, collected across different disciplines.

- Describe the data used or collected.

The “World’s Biggest Data Breaches & Hacks” dataset is adopted for analysis. The dataset contains variables including year, date, sector, method, and data sensitivity, spanning from 2003 to 2023. The long record of data gives them a chance to do a comprehensive analysis.

- Describe how the research question will be answered, e.g. what approaches/methods will be used.

They are going to develop a shiny app with a dashboard that incorporates dropdown menus, sliders, and checkboxes for data filtering. They are going to make a time series of records lost by sector to distinguish anomalies and if possible, mapping the geographical distribution of data breaches. The visualizations for the second question are not mentioned.

- Is there anything that is unclear from the proposal?

The proposal is structured and informative but could be improved by detailing the statistical or analytical methods planned for identifying trends and correlations, such as predictive modeling, cluster analysis, or anomaly detection techniques. Clarification on how 'data sensitivity' levels will be analyzed or interpreted in the context of breaches would provide a more comprehensive understanding of your analytical approach.

- Provide constructive feedback on how the team might be able to improve their project.

Can place a stronger emphasis on comparing the frequency, severity, and methods of breaches across different sectors over time to yield insightful distinctions and similarities.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

Excited about analyzing the relationship between the sensitivity of compromised data in breaches and the subsequent impacts on organizations and individuals, offering insights into the real-world consequences of cybersecurity failures.

- Provide constructive feedback on any issues with file and/or code organization.

The recods.lost column is a wide-range column, meaning that it has a wide range of values, from very low to very high, which makes the comparison and trend analysis difficult.

- (Optional) Any further comments or feedback?

Engaging with cybersecurity experts for validation of findings or to gain deeper insights, might ensure the practical applicability and depth of your recommendations and analyses.

**Comment by Abhi291712** [comment]
Thanks for your valuable feedback. 
We have incorporated the changes suggested by you into our proposal.
